name: onboard
description: Flutter package that provides an iOS-style onboarding experience. Improved from cupertino_onboarding
version: 1.0.1
repository: https://github.com/ArcaneArts/onboard
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  dots_indicator: ^2.1.0
  flutter:
    sdk: flutter
dev_dependencies:
  dart_code_metrics: ^5.4.0
  import_sorter: ^4.6.0
  very_good_analysis: ^3.1.0
